# Generated by Django 4.0.5 on 2022-12-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'avtor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='kategorija',
            fields=[
                ('id_na_kategorija', models.IntegerField(primary_key=True, serialize=False)),
                ('ime_na_kategorija', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'kategorija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='kupuvac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drzava', models.CharField(max_length=100)),
                ('grad', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('broj', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kupuvac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='kupuvac_kupuva_umetnicko_delo',
            fields=[
                ('id_kupuvac', models.IntegerField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField()),
            ],
            options={
                'db_table': 'kupuvac_kupuva_umetnicko_delo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='naracka',
            fields=[
                ('id_naracka', models.IntegerField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('datum', models.DateTimeField()),
            ],
            options={
                'db_table': 'naracka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='posetitel_na_aplikacijata',
            fields=[
                ('id_na_posetitel', models.IntegerField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=150)),
                ('prezime', models.CharField(max_length=150)),
                ('e_mail_adresa', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('telefonski_broj', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'posetitel_na_aplikacijata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='umetnicko_delo',
            fields=[
                ('id_na_umetnicko_delo', models.IntegerField(primary_key=True, serialize=False)),
                ('ime_na_umetnicko_delo', models.CharField(max_length=100)),
                ('dimenzija', models.CharField(max_length=100)),
                ('slika_od_umetnicko_delo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'umetnicko_delo',
                'managed': False,
            },
        ),
    ]
